//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DotNet.Analyzers.Compatibility {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.DotNet.Analyzers.Compatibility.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string AboutDiagnosticFormatString {
            get {
                return ResourceManager.GetString("AboutDiagnosticFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is unsupported on .NET Core. Use Tasks instead..
        /// </summary>
        internal static string BeginInvokeEndInvokeAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BeginInvokeEndInvokeAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate.BeginInvoke and EndInvoke are unsuported on .NET Core.
        /// </summary>
        internal static string BeginInvokeEndInvokeAnalyzerTitle {
            get {
                return ResourceManager.GetString("BeginInvokeEndInvokeAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse to {0}.
        /// </summary>
        internal static string BrowseToUrlFormat {
            get {
                return ResourceManager.GetString("BrowseToUrlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocId,Namespace,Type,Member,DiagnosticIds
        ///M:System.Environment.get_OSVersion,System,Environment,get_OSVersion(),DE0009
        ///F:System.PlatformID.MacOSX,System,PlatformID,MacOSX,DE0007
        ///F:System.PlatformID.Win32S,System,PlatformID,Win32S,DE0007
        ///F:System.PlatformID.Win32Windows,System,PlatformID,Win32Windows,DE0007
        ///F:System.PlatformID.WinCE,System,PlatformID,WinCE,DE0007
        ///F:System.PlatformID.Xbox,System,PlatformID,Xbox,DE0007
        ///M:System.Collections.ArrayList.#ctor,System.Collections,ArrayList,.ctor(),DE0006
        ///M:S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Deprecated {
            get {
                return ResourceManager.GetString("Deprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is deprecated.
        /// </summary>
        internal static string DeprecatedAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("DeprecatedAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API is deprecated.
        /// </summary>
        internal static string DeprecatedAnalyzerTitle {
            get {
                return ResourceManager.GetString("DeprecatedAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} isn&apos;t supported on {1}.
        /// </summary>
        internal static string ExceptionAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("ExceptionAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API not supported on all platforms.
        /// </summary>
        internal static string ExceptionAnalyzerTitle {
            get {
                return ResourceManager.GetString("ExceptionAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocId,Namespace,Type,Member,linux,osx,win
        ///M:Microsoft.Win32.PowerModeChangedEventArgs.#ctor(Microsoft.Win32.PowerModes),Microsoft.Win32,PowerModeChangedEventArgs,.ctor(PowerModes),X,X,
        ///M:Microsoft.Win32.PowerModeChangedEventArgs.get_Mode,Microsoft.Win32,PowerModeChangedEventArgs,get_Mode(),X,X,
        ///&quot;M:Microsoft.Win32.Registry.GetValue(System.String,System.String,System.Object)&quot;,Microsoft.Win32,Registry,&quot;GetValue(String, String, Object)&quot;,X,X,
        ///&quot;M:Microsoft.Win32.Registry.SetValue(System.String,System.String,S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Exceptions {
            get {
                return ResourceManager.GetString("Exceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name,ModuleName
        ///abort,api-ms-win-crt-runtime-l1-1-0.dll
        ///abs,api-ms-win-crt-utility-l1-1-0.dll
        ///accept,ws2_32.dll
        ///AcceptEx,mswsock.dll
        ///acos,api-ms-win-crt-math-l1-1-0.dll
        ///acosf,api-ms-win-crt-math-l1-1-0.dll
        ///acosh,api-ms-win-crt-math-l1-1-0.dll
        ///acoshf,api-ms-win-crt-math-l1-1-0.dll
        ///acoshl,api-ms-win-crt-math-l1-1-0.dll
        ///AcquireSRWLockExclusive,api-ms-win-core-synch-l1-1-0.dll
        ///AcquireSRWLockExclusive,api-ms-win-core-synch-l1-2-0.dll
        ///AcquireSRWLockExclusive,api-ms-win-core-synch-l1-2-1.dll
        ///AcquireSR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModernSdk {
            get {
                return ResourceManager.GetString("ModernSdk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}!{1} isn&apos;t available in UWP.
        /// </summary>
        internal static string ModernSdkAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("ModernSdkAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native API not available in UWP.
        /// </summary>
        internal static string ModernSdkAnalyzerTitle {
            get {
                return ResourceManager.GetString("ModernSdkAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocId,Namespace,Type,Member
        ///M:System.AppContext.GetData(System.String),System,AppContext,GetData(String)
        ///M:System.AppContext.get_TargetFrameworkName,System,AppContext,get_TargetFrameworkName()
        ///T:System.StringNormalizationExtensions,System,StringNormalizationExtensions,
        ///T:System.Data.Common.DbColumn,System.Data.Common,DbColumn,
        ///T:System.Data.Common.DbDataReaderExtensions,System.Data.Common,DbDataReaderExtensions,
        ///T:System.Data.Common.IDbColumnSchemaGenerator,System.Data.Common,IDbColumnSchemaGenerator, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Net461 {
            get {
                return ResourceManager.GetString("Net461", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} isn&apos;t available in .NET Framework 4.6.1.
        /// </summary>
        internal static string Net461AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("Net461AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API not available in .NET Framework 4.6.1.
        /// </summary>
        internal static string Net461AnalyzerTitle {
            get {
                return ResourceManager.GetString("Net461AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report an issue with {0}.
        /// </summary>
        internal static string ReportAnIssueFormatString {
            get {
                return ResourceManager.GetString("ReportAnIssueFormatString", resourceCulture);
            }
        }
    }
}
